### ISSUE TITLE
Sample code in README.md

### ISSUE THREAD

**Issue by Yamaguchi** [visvirial/lninvoice#1]
Hi, I have a problem about sample code in README.md.
It does not work for me...

```
$ node test.js 
module.js:557
    throw err;
    ^

Error: Cannot find module './dist/LNInvoice'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/h_yamaguchi/Documents/Projects/my/lninvoice/test.js:1:81)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by visvirial** [comment]
This is fixed in #1.
